DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;

USE burgers_db;
CREATE TABLE burgers (
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(30) UNIQUE NOT NULL,
quantity INT UNSIGNED NOT NULL,
cost DOUBLE UNSIGNED NOT NULL,
purchased BOOLEAN NOT NULL
);